### PR TITLE
Allow multiple settings objects to be used within a single page

### PR DESCRIPTION
**Pull request by tgjones**
I've added set-specific variable names for each of the settings objects. When you include multiple sets in your application.js file, this change allows you to differentiate between the settings objects. This is necessary when you want to have multiple MarkItUp editors on a single page, each using different sets.

(This is a backwards-compatible change: I've left the existing "mySettings" variables in place.)

The only downside I can see is that, if and when this gem needs to be upgraded with new set files, these changes will need to be re-applied. I consider this useful enough to be worth that overhead; hopefully you do too.

### CODE REVIEW

**Comment by uri** [comment]
Will review asap.

**Comment by phlipper** [comment]
@tgjones thanks for this! Unfortunately this can't be merged at the moment. Can you please rebase against the latest master? Thanks!

**Comment by tgjones** [comment]
I have rebased against the latest master, and removed the image-url commit, which I notice has already been fixed (albeit in a more hard-coded way).

**Comment by phlipper** [comment]
@tgjones thank you very much!

**Pull request merged**
